server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/metaro
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ohgiraffers
    password: ohgiraffers
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 262c56061ee06d4004d2f9b94db133a4
            client-secret: phbHwOkx5MW5SsIdu3wRgo59BH9nF2kb
            redirectUri: http://localhost:8080/api/auth/kakao/login
            authorization-grant-type: authorization_code
            scope: [ profile,account_email ]
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: 7ZmA656AIOuTneygkOyZlSDquLDsm5AgMeydvOywqALdlsKJL3234jklsdjfaKJDLnflkasdf

logging:
  level:
    '[company.gonggam]': DEBUG
    '[org.hibernate.type]': TRACE